name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:lts
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Run tests
      if: github.event_name == 'pull_request' || github.ref == 'refs/heads/master'
      run: npm test
    - name: Run linting
      run: npm run-script lint

  publish:
    runs-on: ubuntu-latest
    container: node:lts
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Publish
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: node publish-ci.js
