name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    container: node:lts
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: npm install
    - name: Run linting
      run: npm run-script lint
    - name: Run tests
      run: npm test -- --coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1

  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    container: node:lts
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: npm install
    - name: Publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: node ./.bin/publish-ci.js
