name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      if: github.event_name == 'pull_request' || github.ref == 'refs/heads/master'
      uses: docker://node:lts
      with:
        args: sh -c "cd /github/workspace && make test"

    - name: Publish
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: docker://node:lts
      with:
        args: sh -c "cd /github/workspace && make publish-ci NPM_TOKEN=${{ secrets.NPM_TOKEN }}"
